### ISSUE TITLE
「セッションが切れているため、再読み込みを行って再度投稿してください。」のメッセージで投稿ができない。

### ISSUE THREAD

**Issue by mshigaseirin** [rararax16/GAS-SNS-BOARD#1]
GASの初心者です。readmeを見ながらGIHUBよりソースを落とし、スプレッドシートとフォルダを指定の通り作成し、共有設定をしましたが、下記のエラーがでて投稿ができなくて困っています。
「n-rsvvdrn64ha7mhlssggg6wistows4ebp3ums3dy-0lu-script.googleusercontent.comに埋め込まれているページの内容　セッションが切れているため、再読み込みを行って再度投稿してください。」とメッセージが表示されて投稿ができないのですが、原因が分からず困っております。お忙しいところ恐縮ですが、解決策をご教授いただければ幸いと思っておりますので、宜しくお願い致します。

**Comment by rararax16** [comment]
アクセスキーがスプレッドシートのセルの書式までを確認するようにしていたのが原因です。
プログラム的にはそこまで確認しなくても良いと思ったので、書式までは見ないように修正しています。
